name: manage-azure-policy-c0f6ecbb
on:
  workflow_dispatch:
    inputs:
      remarks:
        description: 'Reason for triggering the workflow run'
        required: false
        default: 'Updating Azure Policies'


## Uncomment the following if you wish to automatically trigger workflow run with every commit
#
#  push:
#    paths:
#      - 'initiatives/Azure_Security_Benchmark_1f3afdf9-d0c9-4c3d-847f-89da613e70a8/**'
#      - 'initiatives/FedRAMP_High_d5264498-16f4-418a-b659-fa7ef418175f/**'
#      - 'initiatives/_Preview_CMMC_Level_3_b5629c75-5c77-4422-87b9-2509e680f8de/**'
#      - 'initiatives/CIS_Microsoft_Azure_Foundations_Benchmark_v1.3.0_612b5213-9160-4969-8578-1518bd2a000c/**'
#      - 'initiatives/NIST_SP_800-53_Rev._4_cf25b9c1-bd23-4eb6-bd2c-f4f3ac644a5f/**'
#      - 'initiatives/CIS_Microsoft_Azure_Foundations_Benchmark_v1.1.0_1a5bb27d-173f-493e-9568-eb56638dde4d/**'
#      - .github/workflows/manage-azure-policy-c0f6ecbb.yml
jobs:
  apply-azure-policy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZURE_CREDENTIALS_c0f6ecbb}}
        allow-no-subscriptions: true
    - name: Create or Update Azure Policies
      uses: azure/manage-azure-policy@v0
      with:
        paths: |
          initiatives/Azure_Security_Benchmark_1f3afdf9-d0c9-4c3d-847f-89da613e70a8/**
          initiatives/FedRAMP_High_d5264498-16f4-418a-b659-fa7ef418175f/**
          initiatives/_Preview_CMMC_Level_3_b5629c75-5c77-4422-87b9-2509e680f8de/**
          initiatives/CIS_Microsoft_Azure_Foundations_Benchmark_v1.3.0_612b5213-9160-4969-8578-1518bd2a000c/**
          initiatives/NIST_SP_800-53_Rev._4_cf25b9c1-bd23-4eb6-bd2c-f4f3ac644a5f/**
          initiatives/CIS_Microsoft_Azure_Foundations_Benchmark_v1.1.0_1a5bb27d-173f-493e-9568-eb56638dde4d/**
